default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
      - id: prettier-check
        name: prettier --check
        language: system
        entry: bun run format:check
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

      - id: astro-check
        name: astro check
        language: system
        entry: bun run check
        pass_filenames: false
        always_run: true
        stages: [pre-push]
